FROM scratch
ADD rootfs.tar.gz  / 
ENV LD_LIBRARY_PATH=/lib/:/lib64/:/lib32/:/libx32/:/usr/local/jdk-17.0.11/lib/   JAVA_HOME=/usr/local/jdk-17.0.11/  PATH=/bin/:/usr/sbin/:/usr/local/jdk-17.0.11/bin/
CMD ["java", "-version"]
